### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by yaakovfeldman** [hebcal/hebcal-es6#129]
Hebcal is great.

I note that the various repos in the hebcal organisation are under a variety of licences.

I would like to use hebcal in my website's frontend but under the GPL this may only be possible if my website is open source, including the original unbundled js files.  For this reason relatively few NPM packages are GPL. There is some conflicting advice at https://softwareengineering.stackexchange.com/questions/181082/can-i-use-a-gpl-licensed-piece-of-javascript-on-a-commercial-website and https://opensource.stackexchange.com/questions/4360/what-are-the-implications-of-licensing-a-javascript-library-under-gpl

Please will you confirm if this package can be used by a website that is not open source?

**Comment by mjradwin** [comment]
Hi, thanks so much for the feedback and for using Hebcal.

hebcal/hebcal, hebcal/hebcal-es6, and hebcal-swift are GPL because they are derived from sources originally released under GPL (in particular, the Emacs-Lisp code by Dershowitz & Reingold). Alas, we can't change the license of these repos.

Other repos, especially those authored solely by me, are typically licensed with the BSD 2-Clause license. Having spent much of my professional career in software engineering, I prefer BSD or the MIT licenses because they are more liberal / commercial friendly and less "religious" than GPL. 

I can't confirm or vouch for whether GPL software can be used for a website that's not open source. I'm not a lawyer so I can't give advice. I am aware that there are many many closed-source websites run by huge companies that are deployed on Linux, and we all know that Linux is GPL, so perhaps there are some inferences you could draw about how GPL software can be used when it's library or component of a larger system.
