### ISSUE TITLE
Weekday Torah Reading Leyning?

### ISSUE THREAD

**Issue by michaeleherman** [hebcal/hebcal-es6#228]
Via the API, is there a way to get the weekday Torah leyning? I know it's the first aliyah broken up into 3 parts but it would be handy to be able to pull that from the response as well.

**Comment by mjradwin** [comment]
Thanks for the suggestion. This should be a very straightforward change. We'll implement it soon.

**Comment by mjradwin** [comment]
Rather than try to add weekday Torah reading to existing Jewish calendar API, we're experimenting with the idea of having a dedicated Leyning API that includes full kriyah for Shabbat and holidays, Triennial (optionally) for Shabbat, and weekday readings on Mondays & Thursdays.

We'd love your feedback before we finalize this new API. 

Can you take a look? Here's the basic URL format for Diaspora:

https://www.hebcal.com/leyning?cfg=json&start=2022-09-21&end=2022-09-26

And Israel:

https://www.hebcal.com/leyning?cfg=json&start=2024-06-12&end=2024-06-15&i=on

Note how for Israel on Thursday 2024-06-13 it shows the regular weekday Torah reading because there is only one day of Shavuot b'aretz. If you drop the &i=on from the URL (or set to &i=off, which is the default) it gives Diaspora chag reading for 2nd day Shavuot.

**Comment by mjradwin** [comment]
Hi @michaeleherman, Shana Tova!

Were you able to take a look at the proposed API?

**Comment by mjradwin** [comment]
Documented and released this API. 

https://www.hebcal.com/home/4277/leyning-torah-reading-api
