### ISSUE TITLE
HDate.render([locale]) is not implemented.

### ISSUE THREAD

**Issue by majortom64** [hebcal/hebcal-es6#4]
While the docs specifies that it accepts a locale, it has not been implemented.

**Comment by mjradwin** [comment]
Can you confirm that you're using @hebcal/core 1.2.0 or later? We have tested this and it works just fine:

```js
import {HDate, common} from '@hebcal/core';

const hd = new HDate(15, common.months.CHESHVAN, 5769);
console.log(hd.render()); // '15 Cheshvan 5769'
console.log(hd.render('he')); // '15 חֶשְׁוָן 5769'
```

The right-to-left doesn't render very beautifully here on GitHub, but the string produced by `HDate.render()` is actually always in the format `DD MM YYYY` - if you use `render('he')` the `MM` will be in Hebrew instead of English transliteration.

Note if you want to use gematriya to also render the day and year in Hebrew letters, you'll want to use the related class `HebrewDateEvent` as follows:

```js
import {HDate, HebrewDateEvent, common} from '@hebcal/core';

const hd = new HDate(15, common.months.CHESHVAN, 5769);
const ev = new HebrewDateEvent(hd);
console.log(ev.render()); // '15th of Cheshvan, 5769'
console.log(ev.render('he')); // 'ט״ו חֶשְׁוָן תשס״ט'
```

**Comment by mjradwin** [comment]
We've also added `hDate.renderGematriya()` in `@hebcal/core` 2.0.0

https://github.com/hebcal/hebcal-es6#HDate+renderGematriya

**Comment by majortom64** [comment]
Thanks, that works now (mostly). It will not be displayed here correctly, but it adds a th to the date in Hebrew if one does not use Gematriya.

`י״ד תַּמּוּז תש״פ 14th תַּמּוּז, 5780` (If that is rendered RTL it is `5780 תַּמּוּז [placeholder] 14th`).

The [placeholder] is not really there, just added to get the 14th on the right side.
