### ISSUE TITLE
Channukah is on the wrong day

### ISSUE THREAD

**Issue by asgh** [hebcal/hebcal-es6#90]
This https://www.hebcal.com/hebcal?v=1&maj=on&min=on&nx=on&mf=off&ss=off&mod=off&i=off&d=on&D=off&o=on&a=off&c=off&s=on&F=off&geo=none&lg=h&yt=H&year=5782

Is putting the square for Channukah on Sunday, the 24 of Kislev. Yes Channukah is at night, but that's always like that - Channukah should be placed on the next day, just like all the Holidays are.

**Comment by mjradwin** [comment]
Hi, thanks for using Hebcal and thanks for the feedback.

Hebcal has been displaying Chanukah like this for almost 30 years. Although it's less consistent with other how other holidays are displayed, we find that it is the clearest way to represent the most important information about Chanukah in a compact way.

Note that if you enable candle lighting times for your location, the Chanukah daily events become timed events instead of all-day events.

Lastly, if you click through to the Chanukah detail page, you will see a table that clarifies when Chanukah candles may be lit (at sunset on weekdays, before Shabbat on Friday, and after Havdalah on Saturday night).

https://www.hebcal.com/holidays/chanukah-2021
